### PR TITLE
Start with Vue

### LINKED ISSUE #179: make entry form fit width of screen & less high
### Steps to reproduce
1. Open announcement center on a smartphone browser

### Expected behaviour
Title and body form fields are wider than the screen width.
Announcements are only visible after alot of scrolling down.

### Actual behaviour
Title and body form fields fit the screen width, also on smaller screens.
Body form field is only two lines high so you can see the first announcement (below input area) right away, without scrolling.

**Nextcloud version:** 18.1

**App version** 3.7.0

### LINKED ISSUE #217: 🖌️ Design review comments
cc @ma12-co @jancborchardt @nickvergessen 

## General

- [x] Make sure variables are used
- [ ] Possibly think about better app icon, maybe https://material.io/resources/icons/?search=announcement&icon=campaign&style=baseline

## New announcement composer

- [x] Center all content, widht 670px like in Talk
- [x] Some more space on top, e.g. 80px
- [x] Disable "Announce" button while subject is empty
- [x] Inline validation for too long announcement title
- [x] Remove "Add announcement" heading and instead change "Subject…" placeholder to "New announcement subject"
- [x] Textarea placeholder to "Write announcement text, Markdown can be used …"
- [x] Style the "Subject" field as h2, incl bolding
- [x] Reduce default height of textarea to 3 rows and use autosize to automatically size the height (remove the drag handle too)
- [x] "Advanced options" into 3 dot menu
- [x] Make sure buttons are 44px min
- [x] "Announce" button should go to the right
- [ ] "Announce" button could include targets, like "Announce to everyone" or "Announce to engineering group", "Announce to marketing and 3 more groups"
- [x] Group selection can then also go into 3-dot-menu
- [ ] Think about if elements should be included like Text app parts for basic formatting like bold etc, or the emoji picker

## Announcement list

- [x] Fade/cut long announcement texts after 5 lines, just like in comments. Click toggles expand/collapse
- [x] Subline: Alice Ada 19 minutes ago, visible to everyone (as text, not icon), 0 comments
- [x] "Clear notifications" and "Delete announcement" should go to a 3-dot menu on the right
- [x] Remove horizontal divider line
- [x] position:sticky the header part of each announcement, use same white to transparent fade as in mail heading
- [x] "5 comments" put below the text, on the left – only clicking that should open the sidebar
- [x] Title subline and "5 comments" in var(--color-text-maxcontrast)

## Dashboard widget

- [ ] "New announcement" button in emptycontent

## Notifications

- [x] Remove "quotation marks" from title

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #179
Fix #217 

## General

- [x] Make sure SCSS variables are used
- [x] Center all content, width 670px like in Talk
- [ ] Requires https://github.com/nextcloud/nextcloud-vue/pull/1250

## New announcement composer

- [x] Some more space on top, e.g. 80px
- [x] Disable "Announce" button while subject is empty
- [x] Inline validation for too long announcement title
- [x] Remove "Add announcement" heading and instead change "Subject…" placeholder to "New announcement subject"
- [x] Textarea placeholder to "Write announcement text, Markdown can be used …"
- [x] Style the "Subject" field as h2, incl bolding
- [x] Reduce default height of textarea to 3 rows and use autosize to automatically size the height (remove the drag handle too)
- [x] "Advanced options" into 3 dot menu
- [x] Make sure buttons are 44px min
- [x] "Announce" button should go to the right
- [ ] "Announce" button could include targets, like "Announce to everyone" or "Announce to engineering group", "Announce to marketing and 3 more groups"
- [x] Group selection can then also go into 3-dot-menu
- [ ] Think about if elements should be included like Text app parts for basic formatting like bold etc, or the emoji picker

## Announcement list

- [x] Fade/cut long announcement texts after 5 lines, just like in comments. Click toggles expand/collapse
- [x] Subline: Alice Ada 19 minutes ago, visible to everyone (as text, not icon), 0 comments
  - [x] Missing support for the group list (we only have the ids at the moment, not the display names)
- [x] "Clear notifications" and "Delete announcement" should go to a 3-dot menu on the right
- [x] Remove horizontal divider line
- [x] position:sticky the header part of each announcement, use same white to transparent fade as in mail heading
- [x] "5 comments" put below the text, on the left – only clicking that should open the sidebar
  - [x] Actually open the sidebar
- [x] Title subline and "5 comments" in var(--color-text-maxcontrast)
- [ ] Markdown rendering is missing

### CODE REVIEW

**Comment by nickvergessen** [comment]
Design-wise the announcements list is ready:
Bildschirmfoto von 2020-10-04 14-18-32

**Comment by nickvergessen** [comment]
Bildschirmfoto von 2020-10-04 16-19-07

Need some help on moving the group selection in place. Also I'm not too sure about this point:
> "Announce" button could include targets, like "Announce to everyone" or "Announce to engineering group", "Announce to marketing and 3 more groups"

Would make the code rather complex, but yeah then the selection could be moved to the `…` menu I guess?

cc @jancborchardt @ma12-co

**Comment by jancborchardt** [comment]
Nice work! :)

Now that we collapse the content of announcements, I think we don’t need the sticky header anymore. It looks a bit off to have it sticky even though it’s collapsed.

> >   "Announce" button could include targets, like "Announce to everyone" or "Announce to engineering group", "Announce to marketing and 3 more groups"
>
> Would make the code rather complex, but yeah then the selection could be moved to the … menu I guess?

Yep – while it would make the code more complex, it would make the interface nice and clean. :)

**Comment by nickvergessen** [comment]
Raised issues for the missing group selection and markdown support, so we can finally get this PR in.

**Pull request merged**
