### PR TITLE
No activities and notifications for excluded guests

### LINKED ISSUE #188: Users of the guest app which are excluded from this app get notifications
The receive activities and notifications, can read the subject and the message but can not access the app afterwards.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #188

### CODE REVIEW

**Comment by JorisBodin** [comment]
Don't work?
I've just received a new notification
image

**Comment by nickvergessen** [comment]
Well you just got the last notification like this and the mentioned updates will bring in this update ;)

**Pull request merged**
