### PR TITLE
Multiple fixes, enhancements, and styling upgrades

### PR DESCRIPTION
**Pull request by SLYtiger16**
In reference to issue #180 this adds a close button to the comment side-bar to enable easier closing on smaller screens without a refresh.

Signed-off-by: Kyle Meadows <Kyle.Meadows@610ind.com>

### CODE REVIEW

**Comment by SLYtiger16** [comment]
@nickvergessen I noticed there was another open and older PR, are you all accepting PR's for this app?

**Comment by nickvergessen** [comment]
Yeah, just not sure about the other one as when it gets merged we cant do some other planned stuff anymore, like sending the text via email and stuff.

**Comment by SLYtiger16** [comment]
@nickvergessen One last question and I will quit bothering. Which branch would you prefer PR's on? I have another one I want to request today to cover #179 with additional styling fixes for mobile phones and desktop.

**Comment by SLYtiger16** [comment]
This now has a fix for #172 as well.

**Comment by SLYtiger16** [comment]
@nickvergessen what can be done to assist in the review and merge then upgrade of Tasks?

**Comment by nickvergessen** [comment]
I will check this out tonight or tomorrow

**Comment by nickvergessen** [comment]
For the future it's best to do one PR per fix,
I will split it up for now and also invite you to our org, so you can create your PRs based on branches in this repo directly.

**Comment by SLYtiger16** [comment]
Apparently the invitation has expired. May I request another invite? @nickvergessen

**Comment by SLYtiger16** [comment]
Closing to implement incremental PR's

**Pull request closed without merging**
